### ISSUE TITLE
Segmentation fault on v6.20.0 when API HTTP enabled

### ISSUE THREAD

**Issue by HaloGenius** [MoneroOcean/xmrig#120]
Linux builds v6.20.0 when HTTP API enabled in JSON config caused to Segmentation fault when Ghostrider algo benchmark started 
Reproduced on:
- compact build from the repository
- build from sources with GCC 10.3.0

Fixed when this commit ignored https://github.com/MoneroOcean/xmrig/commit/ae2b7e3348374a75b44fa3ee4c1229ac2435a6d6

Works fine on the original XMRig. So the most obvious thing here is that there is a conflict with benchmarking

**Comment by leonelsr** [comment]
I can confirm the same happens on Windows 10, with the v6.20.0 binaries from this repository, with or without **xmrig-cuda** plugin enabled.
