### ISSUE TITLE
Compiling with KawPow disabled fails.

### ISSUE THREAD

**Issue by akku1139** [MoneroOcean/xmrig#126]
**Describe the bug**
If WITH_KAWPOW is disabled in CMakeLists.txt, it will not build correctly.

**To Reproduce**
Edit `CMakeLists.txt` and set `WITH_KAWPOW` to `OFF`.
`option(WITH_KAWPOW          "Enable KawPow algorithms family" OFF)`

**Expected behavior**
Compilation will run to completion.

**Required data**
None

**Additional context**
I made the following changes and it compiled successfully.
```
$ git diff src/base/net/stratum/Pool.h
diff --git a/src/base/net/stratum/Pool.h b/src/base/net/stratum/Pool.h
index a994798..413a31c 100644
--- a/src/base/net/stratum/Pool.h
+++ b/src/base/net/stratum/Pool.h
@@ -46,7 +46,7 @@ public:
         MODE_POOL,
         MODE_DAEMON,
         MODE_SELF_SELECT,
-#       ifdef XMRIG_ALGO_KAWPOW
+#       if defined XMRIG_ALGO_KAWPOW || defined XMRIG_ALGO_GHOSTRIDER
         MODE_AUTO_ETH,
 #       endif
 #       ifdef XMRIG_FEATURE_BENCHMARK
@@ -155,7 +155,7 @@ private:
     bool m_submitToOrigin           = false;
     Coin m_coin;
     int m_keepAlive                 = 0;
-#   ifdef XMRIG_ALGO_KAWPOW
+#   if defined XMRIG_ALGO_KAWPOW || defined XMRIG_ALGO_GHOSTRIDER
     Mode m_mode                     = MODE_AUTO_ETH;
 #   else
     Mode m_mode                     = MODE_POOL;
```

I checked the upstream XMRig and there was no branch option there.
https://github.com/xmrig/xmrig/blob/master/src/base/net/stratum/Pool.h#L49

**Comment by realsetvin** [comment]
Thanks for the report. Would you be able to take time to submit a pull request, as I dont feel confident enough to make the changes myself.

**Comment by Spudz76** [comment]
I must have already fixed this in my own dev tree (that I build and run from) and will see what the fix was and separate it into a PR.

**Comment by Spudz76** [comment]
Okay it was exactly as described by OP :)
