### ISSUE TITLE
set WITH_KAWPOW OFF will case segment fault

### ISSUE THREAD

**Issue by CodeRoboto** [MoneroOcean/xmrig#47]
**Describe the bug**
Building in apline docker image, if I set `WITH_KAWPOW` to `OFF` in `CMakeLists.txt`, it gives me a segment fault.

**To Reproduce**
apline docker image
static build
disable WITH_KAWPOW
run it with any config

**Comment by CodeRoboto** [comment]
PS: the original `xmrig/xmrig` will not cause this crash

**Comment by Spudz76** [comment]
I have a patch for this already submitted #44 if anyone ever awakes and merges it... :)

**Comment by CodeRoboto** [comment]
Maybe I need to apply your patch locally after git pull.

**Comment by Spudz76** [comment]
Has been merged a while ago, has the issue been fixed for you?  Please close if so.
