### ISSUE TITLE
CN/GPU not working on Linux

### ISSUE THREAD

**Issue by PuppyLover101** [MoneroOcean/xmrig#50]
Tested on: Ubuntu 20.04 / Lubuntu 20.04 / Manjaro 21.02

``[2021-04-26 16:33:50.362]  opencl   use profile  cn/gpu  (2 threads) scratchpad 2048 KB
|  # | GPU |  BUS ID | INTENSITY | WSIZE | MEMORY | NAME
|  0 |   0 | 03:00.0 |       480 |     8 |    960 | Radeon RX550/550 Series (gfx804)
|  1 |   0 | 03:00.0 |       480 |     8 |    960 | Radeon RX550/550 Series (gfx804)
[2021-04-26 16:33:50.380]  opencl   GPU #0 compiling...
[2021-04-26 16:33:50.388]  opencl   error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram
BUILD LOG:
/tmp/OCL18536T7.cl:500:44: error: parameter name omitted
__kernel void cn0(__global ulong *input,int,__global int *Scratchpad,__global ulong *states,uint Threads)
                                           ^
1 error generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

[2021-04-26 16:33:50.388]  opencl   thread #0 failed with error CL_INVALID_PROGRAM
[2021-04-26 16:33:50.396]  opencl   GPU #0 compiling...
[2021-04-26 16:33:50.399]  opencl   thread #0 self-test failed
[2021-04-26 16:33:50.409]  opencl   error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram
BUILD LOG:
/tmp/OCL18536T8.cl:500:44: error: parameter name omitted
__kernel void cn0(__global ulong *input,int,__global int *Scratchpad,__global ulong *states,uint Threads)
                                           ^
1 error generated.

error: Clang front-end compilation failed!
Frontend phase failed compilation.
Error: Compiling CL to IR

[2021-04-26 16:33:50.409]  opencl   thread #1 failed with error CL_INVALID_PROGRAM
[2021-04-26 16:33:50.410]  opencl   thread #1 self-test failed
[2021-04-26 16:33:50.410]  opencl   disabled (failed to start threads)
[2021-04-26 16:34:23.473]  opencl   #0 03:00.0  14W 45C    0RPM 977/300MHz
[2021-04-26 16:34:23.473]  miner    speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s
[2021-04-26 16:35:24.117]  opencl   #0 03:00.0  15W 42C    0RPM 994/300MHz
[2021-04-26 16:35:24.117]  miner    speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s
[2021-04-26 16:36:24.767]  opencl   #0 03:00.0  15W 40C    0RPM 999/300MHz
[2021-04-26 16:36:24.767]  miner    speed 10s/60s/15m n/a n/a n/a H/s max n/a H/s
``

**Comment by Spudz76** [comment]
PR #43 fixes this and has been available for merge forever, but the maintainer here doesn't seem to want bugfixes (I have four pending PR's)

**Comment by mondsen** [comment]
Thanks @Spudz76, your patch helped :)
This fixed the following error building on RP4

`/home/ethereum/xmrig/src/crypto/cn/CnHash.cpp: In constructor ‘xmrig::CnHash::CnHash()’:
/home/ethereum/xmrig/src/crypto/cn/CnHash.cpp:313:64: error: no matches converting function ‘cryptonight_single_hash_gpu’ to type ‘using cn_hash_fun = void (*)(const uint8_t*, size_t, uint8_t*, struct cryptonight_ctx**, uint64_t)’ {aka ‘void (*)(const unsigned char*, long unsigned int, unsigned char*, struct cryptonight_ctx**, long unsigned int)’}
  313 |     m_map[Algorithm::CN_GPU][AV_SINGLE][Assembly::NONE]      = cryptonight_single_hash_gpu<Algorithm::CN_GPU, false, 0>;
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ethereum/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/ethereum/xmrig/src/crypto/cn/CryptoNight_arm.h:624:13: note: candidate is: ‘template<xmrig::Algorithm::Id ALGO, bool SOFT_AES> void xmrig::cryptonight_single_hash_gpu(const uint8_t*, size_t, uint8_t*, cryptonight_ctx**, uint64_t)’
  624 | inline void cryptonight_single_hash_gpu(const uint8_t *__restrict__ input, size_t size, uint8_t *__restrict__ output, cryptonight_ctx **__restrict__ ctx, uint64_t height)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ethereum/xmrig/src/crypto/cn/CnHash.cpp:314:64: error: no matches converting function ‘cryptonight_single_hash_gpu’ to type ‘using cn_hash_fun = void (*)(const uint8_t*, size_t, uint8_t*, struct cryptonight_ctx**, uint64_t)’ {aka ‘void (*)(const unsigned char*, long unsigned int, unsigned char*, struct cryptonight_ctx**, long unsigned int)’}
  314 |     m_map[Algorithm::CN_GPU][AV_SINGLE_SOFT][Assembly::NONE] = cryptonight_single_hash_gpu<Algorithm::CN_GPU, true,  0>;
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ethereum/xmrig/src/crypto/cn/CnHash.cpp:35:
/home/ethereum/xmrig/src/crypto/cn/CryptoNight_arm.h:624:13: note: candidate is: ‘template<xmrig::Algorithm::Id ALGO, bool SOFT_AES> void xmrig::cryptonight_single_hash_gpu(const uint8_t*, size_t, uint8_t*, cryptonight_ctx**, uint64_t)’
  624 | inline void cryptonight_single_hash_gpu(const uint8_t *__restrict__ input, size_t size, uint8_t *__restrict__ output, cryptonight_ctx **__restrict__ ctx, uint64_t height)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
`
