### ISSUE TITLE
Binary for 2.9.3 release

### ISSUE THREAD

**Issue by alexdaums** [MoneroOcean/xmrig#7]
Hello,

Will the binary for version 2.9.3 be added soon?

Thanks.

**Comment by setuidroot** [comment]
I made some Windows 64 bit binaries and posted them here: https://github.com/setuidroot/xmrig/releases

They're clean, made with the latest cmake and MSVC 2017 compiler.  These are **my** binaries, so they're not official or anything... I'm just trying to help out.
