### ISSUE TITLE
RX/0 not working with iGPU vega5

### ISSUE THREAD

**Issue by HighVoltage557** [MoneroOcean/xmrig#72]
I have a vega5 iGPU with driver version 21.8.2, I am using the latest release of xmrig but the hashrate is too high in RX/0 (attached video) and when I use "s" or "c", it shows no active connection and no results yet.

https://user-images.githubusercontent.com/88422812/134633380-3c6ea018-280a-4e44-9cd2-a6e8a5973a1c.mp4

**Comment by Spudz76** [comment]
RandomX not really for GPUs.  Should be using GPU-friendly algos... did algo-perf complete?  Edit algo-perf rx algos to "0.01" so it won't use them.

iGPU terrible anyway, shares system RAM (not VRAM).  Will really hurt CPU mining which needs every bit of memory bandwidth.

**Comment by HighVoltage557** [comment]
Algo perf did not complete due to this, RX/0 just went on, so had to manually set the hashrate. It couldn't complete the rest of algorithms. And when I set RX/0 to false, it gave many lines of error and the benchmark didn't complete in that run too.
Currently, I am just running cn/GPU

**Comment by Spudz76** [comment]
Ah, yes, I generally just compile my GPU miners with `-DWITH_RANDOMX=OFF` so that doesn't happen.

**Comment by HighVoltage557** [comment]
Alright, I will try compiling from the source, I am using the release currently.
