### ISSUE TITLE
question about the cn-heavy mining on first 8 cores instead of the "main" cores?

### ISSUE THREAD

**Issue by G2G2G2G** [MoneroOcean/xmrig#79]
Using an ryzen 3700X
it uses CPU 0 - 7 as xmrig specified in the config, it seems wrong but I could be wrong, was wondering why if it isn't wrong.. can't find anything to read
From the past I learned the main 8 cores would be 0, 2, 4, 6, 8, 10, 12, 14 and the virtual (threads of those cores) ones would be the odd ones?

```
"cn-heavy": [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7]
        ]
```
(that's what xmrig auto-set for it)

From the monero ocean server:
```
 algo cn-heavy/xhv 
```

Thanks!

**Comment by Spudz76** [comment]
Depends which OS:  one of them does it interleaved the other does it sequential.

**Comment by G2G2G2G** [comment]
linux
never heard it differed from windows & linux is there a way to tell in software which is which?

**Comment by Spudz76** [comment]
Yes, `hwloc-ls` [from here for windows](https://download.open-mpi.org/release/hwloc/v2.5/hwloc-win64-build-2.5.0.zip).  Unpack, command prompt, cd to the extracted folder, then `bin`, then run `hwloc-ls`.  On Linux install `hwloc` package and run it.  The `P#` is the processor number, and as you can see below Windows primary cores are P#0 and P#2 while Linux is `P#0/2/4/6`

Windows:
```
C:\Users\miner\Downloads\hwloc-win64-build-2.5.0\bin>hwloc-ls
Machine (5668MB total) + Package L#0
  NUMANode L#0 (P#0 5668MB)
  L3 L#0 (3072KB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#1)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#2)
      PU L#3 (P#3)
```

Linux:
```
Machine (16GB total)
  Package L#0
    NUMANode L#0 (P#0 16GB)
    L3 L#0 (6144KB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#1)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
        PU L#2 (P#2)
        PU L#3 (P#3)
      L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
        PU L#4 (P#4)
        PU L#5 (P#5)
      L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
        PU L#6 (P#6)
        PU L#7 (P#7)
...
```

Of course, maybe they "fixed" it now, so the difference was only on earlier hwloc.  I haven't verified in a while like above (where they seem to be interleaved the same on both).

**Comment by G2G2G2G** [comment]
Thanks, I'll check out that program, I don't actually see a difference in your post (ctrl+f'd each line and they're identical) 
yea idk I've been watching multiple machines closely and have seen it change (on the same machine) running 0-7 core and 8 - 15 cores (weird) same speed though

on one 6 core 12 thread I've seen it using 8 threads lol, but speeds seem to check out vs other people so not really worried, just curious. 


```
Machine (31GB total)
  Package L#0
    NUMANode L#0 (P#0 31GB)
    L3 L#0 (16MB)
      L2 L#0 (512KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
        PU L#0 (P#0)
        PU L#1 (P#8)
      L2 L#1 (512KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
        PU L#2 (P#1)
        PU L#3 (P#9)
      L2 L#2 (512KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
        PU L#4 (P#2)
        PU L#5 (P#10)
      L2 L#3 (512KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
        PU L#6 (P#3)
        PU L#7 (P#11)
    L3 L#1 (16MB)
      L2 L#4 (512KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
        PU L#8 (P#4)
        PU L#9 (P#12)
      L2 L#5 (512KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
        PU L#10 (P#5)
        PU L#11 (P#13)
      L2 L#6 (512KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
        PU L#12 (P#6)
        PU L#13 (P#14)
      L2 L#7 (512KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
        PU L#14 (P#7)
        PU L#15 (P#15)
```

So if I read mine correctly.. the first "core" (thread) 's second one is actually the 8th one?

![1](https://user-images.githubusercontent.com/50514477/141388231-faa5393b-3ea6-4fa8-a7c0-3cc6ba635533.jpg)
So if I am reading htop above (which renames 0 to 1) the 1st and 9th are the same physical core, did I read it correctly?

**Comment by Spudz76** [comment]
Yep yours shows up how I expected one of mine to show, the other layout where all "real" cores are first, then all the "fake" cores.

Instead of all the even numbers are real and odds are fake.

I swear it used to be that way even on same machine dual-booted Win vs Lin... surprised me when mine didn't show the difference (but different machines so it could be how BIOS lays them out).  I think the layout yours shows is like Windows.

At any rate, hwloc should seek the right cores.  It is extra weird if yours switch layouts randomly.  Are you dual-boot?  Maybe booting Windows then warm booting into Linux leaves the layout in Windows mode (vs cold boot direct into either).

**Comment by G2G2G2G** [comment]
Lol yea, after running it on some machines as you said it doesn't seem to be consistent more like a per hardware vs a per operating system.. weird maybe bios as you said.

It didn't "switch layouts" (well maybe it did I didn't look at the config) only the "cn-heavy/xhv" algorithm in miner switched from 0 - 7 to 8 - 15.. when it switched I was maxing out cores 0,1 and 2 (3 cores) doing something else.. I'm not sure if it saw that and was like "fuck those threads" so did the secondary ones? but it hasn't happened since.. maybe I can max out those cores again and leave it to see if it goes to the second set (by second set of cores, just to be 100% clear, my htop image was basically flipped around with the right half maxed and left not) 
and the cores were maxed via KVM and qemu so it was red "kernel" and orange "virtual" usage not sure if that matters for it to have chose the other threads
and no rebooting or anything this is my main desktop it only has 1 distro installed no windows and has probably been up since then, most of my work runs fine while mining in the winter for heat so I just leave it running 24/7  
uptime: `13:45:09 up 16 days, 15:49,  1 user,  load average: 8.27, 8.31, 8.29` <-- mostly it seems to do the cn-heavy one so as far as working/browsing web can't even tell a miner is running tbh

thanks for answering all my questions! I'll close it but if you got more questions on the switch let me know(I get an email from this thread) (it hasn't done it since but I haven't maxed any cores since)

**Comment by G2G2G2G** [comment]
@Spudz76  Just for laughs thought this one was funny
![1](https://user-images.githubusercontent.com/50514477/142972659-0b1376dc-c859-4511-9434-30087ad6d409.jpg)
most of them are pretty steady (however still kinda weird it chose them), but the 6 and 14 threads keep switching lmao
