### ISSUE TITLE
ghostrider algorithm support for RTM mining 

### ISSUE THREAD

**Issue by bellfeige** [MoneroOcean/xmrig#80]
Is there a plan to add ghostrider algorithm into MoneroOcean xmrig to support RTM (Raptoreum) mining?

Official XMRig supports GhostRider algorithm starting from version v6.16.0
[https://github.com/xmrig/xmrig/blob/master/src/crypto/ghostrider/README.md](https://github.com/xmrig/xmrig/blob/master/src/crypto/ghostrider/README.md)

**Comment by Spudz76** [comment]
MO fork gets everything upstream `master` branch gets.  After slight lag to readjust all the modifications...

Doesn't mean the pool will support it for cross-mining.  That depends on TradeOgre having a trade pair for whichever coin<>XMR and somewhat the valuation (if it would never be more lucrative than the top 5 it may not be worth adding, it would never be selected...)

But, the pool already doesn't support every algo xmrig contains, yet you can still directly mine any of them using the MO-fork (although not much reason to do that).

**Comment by Titaniumtown** [comment]
> Doesn't mean the pool will support it for cross-mining. That depends on TradeOgre having a trade pair for whichever coin<>XMR...

Well it doesn't need a trade pair, you simply convert it to BTC then buy the XMR with that BTC which then gets paid to the miners.

**Comment by Spudz76** [comment]
Noticed my rigs are mining GR all of a sudden, therefore this has been resolved.

**Comment by BerdinskiyBear** [comment]
@jfikar If I remember correctly only us-or.moneroocean.stream server currently works with ghostrider.

**Comment by Fyrhus** [comment]
> I'm getting lower than expected hashrate for GR, maybe because the benchmark time is limited and for correct GR hashrate one would need something like 24 hour average.

I think that benchmark checks only one "rotation" of the ghostrider algorithm so the benchmark result doesn't match the average.

**Comment by jfikar** [comment]
@BerdinskiyBear I see, when using us-or.moneroocean.stream xmrig.mo switches to GR. Any idea when the other servers will enable GR?

@Fyrhus it seems the first rotation is slower than average. Probably one can choose another rotation, which has hashrate closer to the average. But I don't mind editing the hashrate by hand.

**Comment by Spudz76** [comment]
> How come? You didn't have to rebench to get the GR algo-perf?

Yes but I did it ahead of time the moment the support was added a couple days before it went live.

**Comment by jmakov** [comment]
Measured that RTM mining is about 20% more profitable than whatever moneroocean_miner is mining. Any estimates when an address in EU will be supported (if I understand correctly only 1 pool address in the US currently supports it)?

**Comment by Jhobean** [comment]
@jmakov what @moneroOcean said on discord is after first bloc find. He need to validate if all system is ok.

**Comment by jmakov** [comment]
@Jhobean thanks for super fast response. Sorry but didn't follow Discord debates. I'm just seeing about 20% diff after about 8h and hope to understand how come. I'd love to use moneroocean_miner but I'm not sure I understand where comes the difference from (did Raptoreum price just jump/XMR went downhil in that time?). Also I noticed moneroocean_miner doesn't sees Raptoreum as most profitable to mine on 5900x for some reason (and again, sorry but I'm still not sure if that's because moneroocean pool doesn't support it or if the miner profitability data is updated 1x day or sth else). Also I think Discord would perhaps be better for such questions of mine, so sorry for hijacking the issue, just confused because of the % diff.

**Comment by Jhobean** [comment]
> @Jhobean thanks for the super fast response. Sorry but didn't follow Discord debates. I'm just seeing about 20% diff after about 8h and hope to understand how come. I'd love to use moneroocean_miner but I'm not sure I understand where comes the difference from (did Raptoreum price just jump/XMR went downhil in that time?). Also I noticed moneroocean_miner doesn't sees Raptoreum as most profitable to mine on 5900x for some reason (and again, sorry but I'm still not sure if that's because moneroocean pool doesn't support it or if the miner profitability data is updated 1x day or sth else). Also I think Discord would perhaps be better for such questions of mine, so sorry for hijacking the issue, just confused because of the % diff.

Come join us and ask all question you like: https://discord.gg/uGkMyWMCsw

**Comment by jmakov** [comment]
I see ghostrider running on a non us-ro node. I suppose this issue can be closed.

**Comment by MoneroOcean** [comment]
Yes. Thank you for reminder!
