### ISSUE TITLE
cn/gpu is broken on 6.16.2-mo2 (cuda) - error Unsupported algorithm

### ISSUE THREAD

**Issue by ataa** [MoneroOcean/xmrig#85]
**Describe the bug**
cn/gpu is broken on the recent release (6.16.2-mo2) when using cuda plugin.

**To Reproduce**
Enable cuda in config.json and run latest MO xmrig.

**Expected behavior**
cn/gpu is working as expected on 6.16.1-mo1 but when upgrading to 6.16.2-mo2 either by building from source or using the binaries, crash the miner during the benchmark with "`nvidia   thread #0 failed with error Unsupported algorithm`" error message.

**Required data**
 - Error message: "`nvidia   thread #0 failed with error Unsupported algorithm`"
 - OS: Tried on Windows 10, Ubuntu 21.10
 - GPU: Tried on 1650 Super, GT 1030, Titan Black and received the same error message. All card have worked fine on 6.16.1-Mo1 using the same cn/gpu algo.

**Additional context**
Someone reported on Discord: 1a9eaaa is where it broke.

**Comment by pmos69** [comment]
Confirm on a 3060ti
Using xmrig-cuda-v6.15.1-mo1-cuda11_3

**Comment by Spudz76** [comment]
Fixed in [this patch](https://github.com/MoneroOcean/xmrig-cuda/pull/5)

**Comment by ataa** [comment]
Thank you. I can confirm that the cn/gpu issue has been resolved in the latest release. However I noticed different issue in the latest release, This time on Kawpow Algo. On the latest release it get successful connection to the pool and submitting shares, but nothing get accepted, And while xmrig is trying to submit the shares, worker name disappear from MO dashboard.
No sure if it's related to the recent patch or not, Please let me know how to debug this.
KawPow is working fine on 6.15.3-mo1, with accepted shares every 17 seconds or so. Cuda plugin details:
CUDA         11.3/11.4/6.15.1-mo2
NVML         11.472.39/472.39
