### ISSUE TITLE
Read error: connection rest by peer and end of file.

### ISSUE THREAD

**Issue by kurokawaikki** [MoneroOcean/xmrig#87]
Hi,
I am new to moneroocean and try to mine this with MO_XMRIG.
I followed the help on the official website.
I choose to use default setting on pool and port.
However, after benchmark, it keeps show the error of connection rest by peer.

So, I change the port number to 20128. I believe SSL might solve the connection problem.
But... the error comes out... Read error: end of file.
I double checked that I did not corrupt the json file.

My rig is amd 5950X running on proxmox hypervisor. The miner is running in virtual machine in win10.

Please help me... Thank you!

**Comment by Spudz76** [comment]
Must set `"tls": true,` along with the 2xxxx port.

**Comment by kurokawaikki** [comment]
OK!
It worked! 
Thank you very much. So it seems that some how the 10128 port was blocked...
Thank you again for the solution. This concludes the issue.
