### ISSUE TITLE
cryptonight-heavy/tube Segmentation Fault

### ISSUE THREAD

**Issue by jmr13031** [MoneroOcean/xmrig#9]
All 4 RPI's receive a Segmentation Fault when switching to cryptonight-heavy/tube algorithm.

 * ABOUT        XMRig/2.14.1-mo1 gcc/8.1.0
 * LIBS         libuv/1.18.0 OpenSSL/3.0.0-dev microhttpd/0.9.51 
 * CPU          ARMv7 (1) -x64 -AES -AVX2

[2019-06-01 09:02:03] new job from server:3333 diff 100 algo cn-heavy/tube height 349649
[2019-06-01 09:02:14] speed 10s/60s/15m n/a n/a n/a H/s max 33.2 H/s
Segmentation fault

**Comment by jmr13031** [comment]
updated to ubuntu-18.04.2-preinstalled-server-arm64+raspi3
updated to 4A 5V power brick.
All seems to be running well..
CN/R = ~7-8 h/s
CN-pico/trtl = ~155 h/s

-  ABOUT        XMRig/2.14.1-mo1 gcc/7.4.0
-  LIBS         libuv/1.18.0 OpenSSL/1.1.1 microhttpd/0.9.59 
-  CPU          ARMv8 (1) x64 -AES -AVX2
-  THREADS      4, cryptonight, donate=4%

**Comment by crocket** [comment]
Why did you close this? I encountered with this issue today.
