### ISSUE TITLE
XMRIG will not free Ram after benchmark

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [MoneroOcean/xmrig#99]
after running xmrig
benchmark started, after benchmark xmrig started to mine Astrobwt
but it does not free 2GB ram that was used to benchmark randomx
after i restarted it, xmrig not used ram anymore because it is not mining randomx

**Comment by Spudz76** [comment]
Correct, that's how it works.  If it released the RandomX memory while running and it switched back to RandomX the memory could be unavailable later (especially hugepages).
